security:
    password_hashers:
        App\Entity\User: { algorithm: auto }

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: login

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/v1/api/auth/login
            stateless: true
            provider: app_user_provider
            json_login:
                check_path: /v1/api/auth/login
                username_path: login
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: App\Security\LoginFailureHandler

        api:
            pattern: ^/v1/api
            stateless: true
            jwt: ~
            provider: app_user_provider

    access_control:
        - { path: ^/v1/api/auth/register, roles: PUBLIC_ACCESS }
        - { path: ^/v1/api/auth/login, roles: PUBLIC_ACCESS }
        - { path: ^/v1/api, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            App\Entity\User:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10