version: "3"

networks:
  backend1:
    driver: bridge

services:

  php:
    container_name: php_${PROJECT_NAME}
    build:
      context: ./
      dockerfile: docker/configs/php/Dockerfile
      args:
        WORKDIR: ${WORKDIR}
    environment:
      WORKDIR: ${WORKDIR}

    volumes:
      - ./:${WORKDIR}
    links:
      - db_mysql
    networks:
      - backend1

  db_mysql:
    image: mysql:latest
    container_name: mysql_${PROJECT_NAME}
    ports:
      - ${DB_PORT}:3306
    environment:
      WORKDIR: ${WORKDIR}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_DATABASE:-root}
      MYSQL_USER: ${DB_USERNAME:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}

    volumes:
      - ./docker/databases/mysql_dump:/docker-entrypoint-initdb.d
    networks:
      - backend1

  nginx:
    image: nginx:latest
    container_name: nginx_${PROJECT_NAME}
    environment:
      WORKDIR: ${WORKDIR}
      HTTP_PORT: ${HTTP_PORT}
      HTTPS_PORT: ${HTTPS_PORT}
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    volumes:
      - ./:${WORKDIR}
      - ./docker/configs/nginx:/etc/nginx/conf.d
      - ./docker/configs/nginx/project.conf.template:/etc/nginx/templates/project.conf.template
      - ./logs/nginx:/var/log/nginx
    links:
      - php
    networks:
      - backend1
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
